import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import {Toaster} from "@/components/ui/toaster"
import {Button} from "@/components/ui/button";
import Link from "next/link";
import {TopBar} from "@/components/topbar/topbar";
import Script from "next/script";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <head>
            <script async src="https://www.googletagmanager.com/gtag/js?id=G-KH6HZW4TYJ"></script>
            <Script id={"analytics"}>
                {"window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'G-KH6HZW4TYJ');"}
            </Script>
            <title>etov</title>
            <script async
                    src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5812287911954412"
                    crossOrigin="anonymous"></script>
        </head>
        <body className={inter.className}>
        {children}
        <Toaster/>
        </body>
        </html>
    )
}
